### creating user
POST http://localhost:3000/api/v1/auth/login

{
    "email": "algt@gmail.com",
    "password": "12346"
}

### register user
POST http://localhost:3000/api/v1/auth/register

{   "username": "mamat1",
    "email": "mamat1@gmail.com",
    "password": "123456"
}